Resolve error in dumps with exponential coordinates value
geomet/geomet pull request #73
Opened 2021-01-16 15:52 UTC by vadikko2

2021-01-16 18:00 UTC, vadikko2 commented
This pull requests resolve issue #72

2021-01-17 06:46 UTC, tomplex commented
Thanks for the report and for the pull request. We use the `round` function here for a specific reason, detailed in #38. I'm not inclined to accept a solution to this which regresses our ability to handle that case properly, as demonstrated in the test case you changed.

2021-01-17 08:06 UTC, vadikko2 commented
> Thanks for the report and for the pull request. We use the `round` function here for a specific reason, detailed in #38. I'm not inclined to accept a solution to this which regresses our ability to handle that case properly, as demonstrated in the test case you changed.

I see that, but you use 16 as default decimals value. In the same time, python has exponential representation for float values, less than 10^-4. You use `split('.')` in the `_round_and_pad` function. That is the reason for the issue #72 i created.

2021-01-17 08:11 UTC, vadikko2 commented
> Thanks for the report and for the pull request. We use the `round` function here for a specific reason, detailed in #38. I'm not inclined to accept a solution to this which regresses our ability to handle that case properly, as demonstrated in the test case you changed.

I will try to change way to resolve the issue.

2021-01-17 09:31 UTC, vadikko2 commented
> Thanks for the report and for the pull request. We use the `round` function here for a specific reason, detailed in #38. I'm not inclined to accept a solution to this which regresses our ability to handle that case properly, as demonstrated in the test case you changed.

@tomplex Have been resolved your demands.

2021-01-17 22:44 UTC, larsbutler requested changes

2021-01-17 22:44 UTC, larsbutler commented on geomet/tests/wkt_test.py
> +            [(6e-6, 16), '0.0000060000000000']
I tested this locally with yet another test case:

```
[(1e16, 3), '10000000000000000.000'],
```

This breaks:

```
ERROR: test (geomet.tests.wkt_test.TestRoundAndPad)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/path/to/proj/geomet/geomet/tests/wkt_test.py", line 1237, in test
    self.assertEqual(expected, wkt._round_and_pad(*args))
  File "/path/to/proj/geomet/geomet/wkt.py", line 203, in _round_and_pad
    rounded += '0' * (decimals - len(rounded.split('.')[1]))
IndexError: list index out of range
```

I have a suggestion for a fix below.

2021-01-17 22:44 UTC, larsbutler commented on geomet/wkt.py
> +    if repr(value).find('e-') == 1:
It's also valid for number representations to have a positive exponent. For example:

```
>>> repr(1e16)
'1e+16'
```

Furthermore, the expected index of the `find()` expression here is not going to work in all cases. For example:

```
>>> repr(3.14e-16).find('e-')
4
>>> repr(3.14e16).find('e-')
-1
```

I would suggest simply replacing line 198 with `if 'e' in repr(value):`.

2021-01-17 22:44 UTC, larsbutler commented on geomet/tests/wkt_test.py
> +            [(6e-6, 16), '0.0000060000000000']
I would advise add the at least the following test cases:

```
            [(1e16, 3), '10000000000000000.000'],
            [(3.14e16, 3), '31400000000000000.000'],
            [(3.14e-16, 18), '0.000000000000000314'],
```

@tomplex Can think of any others cases that would be relevant here?

2021-01-18 07:48 UTC, vadikko2 commented
@larsbutler @tomplex Your change requests have been resolved

2021-01-18 07:52 UTC, vadikko2 reviewed
Your requests have been resolved

2021-01-20 14:19 UTC, larsbutler commented
Great, thanks @vadikko2! The contribution is much appreciated. Could you please do one last thing and update the [AUTHORS.txt](https://github.com/geomet/geomet/blob/master/AUTHORS.txt) file?

(Optionally, if you're interested, please read through https://github.com/geomet/geomet/blob/master/CONTRIBUTING.md and let me know if you would like to become a maintainer.)

2021-01-20 14:20 UTC, larsbutler approved these changes
Looks good to me! Please update the AUTHORS.txt and I'll merge this.

2021-01-20 16:56 UTC, vadikko2 commented
> Looks good to me! Please update the AUTHORS.txt and I'll merge this.

Great! 
Done.

2021-01-20 16:56 UTC, vadikko2 commented
> Great, thanks @vadikko2! The contribution is much appreciated. Could you please do one last thing and update the [AUTHORS.txt](https://github.com/geomet/geomet/blob/master/AUTHORS.txt) file?
> 
> (Optionally, if you're interested, please read through https://github.com/geomet/geomet/blob/master/CONTRIBUTING.md and let me know if you would like to become a maintainer.)

Thanks! I would!

2021-01-20 17:41 UTC, larsbutler commented
@vadikko2 Invite sent. :)

2021-01-20 17:41 UTC, merged